### ISSUE TITLE
[ERROR] Plugin org.fusesource.hawtjni:hawtjni-maven-plugin:1.19-SNAPSHOT or one of its dependencies could not be resolved

### ISSUE THREAD

**Issue by gounthar** [sgjava/java-periphery#2]
Hi there,

first of all, thanks for your work.
I'm following your readme, trying to compile on an OrangePi Zero running Armbian (Debian 11 bullseye, Kernel: armv7l Linux 5.10.60-sunxi).

Here is what I get:

```bash
 mvn -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 clean install "-Dcflags=-I$HOME/include"
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< com.codeferm:java-periphery >---------------------
[INFO] Building Java Periphery 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.fusesource.hawtjni:hawtjni-maven-plugin:jar:1.19-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.289 s
[INFO] Finished at: 2021-11-19T22:29:01+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.fusesource.hawtjni:hawtjni-maven-plugin:1.19-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.fusesource.hawtjni:hawtjni-maven-plugin:jar:1.19-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

Would you know what's going on?

Thanks.

**Comment by sgjava** [comment]
You ran install.sh? If so, check the log files in scripts dir. https://github.com/sgjava/java-periphery#run-script

**Comment by gounthar** [comment]
Yes, I ran `install.sh` and saw no error.
Let me recheck it.

**Comment by sgjava** [comment]
Check all the logs, hawtjni.log, etc, not just install.log. `[ERROR] Plugin org.fusesource.hawtjni:hawtjni-maven-plugin:1.19-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.fusesource.hawtjni:hawtjni-maven-plugin:jar:1.19-SNAPSHOT -> [Help 1]` shows basically hawtjni build failed to me.

**Comment by gounthar** [comment]
I thought the built went fine, but there is an error [at the end](https://gist.github.com/gounthar/fd4b7a767c7672da007f8f6d9eea20ed).
I may have called the script incorrectly...

**Comment by sgjava** [comment]
OK, so the good news is HawtJNI built fine, the root cause is `./install.sh: 150: cd: can't cd to java-periphery`  Make sure you do this from your $HOME (~/) dir.

https://github.com/sgjava/java-periphery#download-project
https://github.com/sgjava/java-periphery#run-script

[cd java-periphery >> $logfile 2>&1](https://github.com/sgjava/java-periphery/blob/c5ed620738a8acc87fbc40f3d629634191f6e3dd/scripts/install.sh#L150)

Clone project into your home and run install.sh without root user access. Use non-root user and don't use sudo.

`[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/root). Please verify you invoked Maven from the correct directory. -> [Help 1]`

You are prompted for root password if needed.

**Comment by gounthar** [comment]
I did everything once again, and this time got a `[INFO] BUILD SUCCESS`.
I guess I was wrong somewhere with the first launch of the script.
Sorry for the false alarm, and thanks for your quick answer.

**Comment by sgjava** [comment]
No worries I'll update readme to make sure you know not to run as root user or sudo. The whole idea is to never use library as a root user.
